id: AF7880AFE
title: Prayer for the Long Life of Dezhung Rinpoche
type: translation
pechas:
- IC6694F59
- IDEDE4E65
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:34:57.688152
  last_modified_at: 2023-01-04 11:34:57.688164
  collections:
  - Dezhung Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  IC6694F59/A5D6: 3B8D
  IDEDE4E65/8AD4: 3B8D
